version: "2"

services:
  neo4j:
    image: neo4j
    ports: 
      - 7474:7474
      - 7373:7373
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  mongo:
    image: mongo
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./share:/tmp/share
    command: mongod --replSet neomongo

  mongo_connector:
    build:
      context: .
      dockerfile: Dockerfile-mongo-neo4j-manager
    links:
      - mongo
      - neo4j
    environment:
      - MONGO_HOST=mongo
      - NEO4J_HOST=neo4j
