version: '3.1'

services:

  kibana:
    image: kibana
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./share:/tmp/share