mongo:
    host: localhost
    user: nouser
    password: nopass
    port: 27017
    db: github_demo
    files: files
    contents: contents
    commits: commits
    reposdemo: repos_demo 
    identifiant: id
kafka:
    servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
    topic: topiccommit

